# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  name: salt_solo
  is_file_root: true
  salt_copy_filter:
    - .kitchen
    - .git
    - .vagrant
  state_top:
    base:
      "*":
        - rsnapshot
  pillars-from-files:
    rsnapshot.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - rsnapshot

platforms:
  - name: ubuntu-16.04
#  - name: centos-7.5
#  - name: ubuntu-18.04

suites:
  - name: default
